import { PinataSDK } from "pinata";
import dotenv from "dotenv";

dotenv.config();

console.log(process.env.PINATA_JWT);
console.log(process.env.GATEWAY_URL);

export const pinata = new PinataSDK({
  pinataJwt: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mb3JtYXRpb24iOnsiaWQiOiI2Y2U3OTQ5NS03M2YyLTQxYjUtODNjZS1jOTg0M2Q5NjhlYjIiLCJlbWFpbCI6ImNvZGUudHVzaGFyMTlAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInBpbl9wb2xpY3kiOnsicmVnaW9ucyI6W3siZGVzaXJlZFJlcGxpY2F0aW9uQ291bnQiOjEsImlkIjoiRlJBMSJ9LHsiZGVzaXJlZFJlcGxpY2F0aW9uQ291bnQiOjEsImlkIjoiTllDMSJ9XSwidmVyc2lvbiI6MX0sIm1mYV9lbmFibGVkIjpmYWxzZSwic3RhdHVzIjoiQUNUSVZFIn0sImF1dGhlbnRpY2F0aW9uVHlwZSI6InNjb3BlZEtleSIsInNjb3BlZEtleUtleSI6IjAzZGY2MjE1ZDYwNWEyYjQzMmEzIiwic2NvcGVkS2V5U2VjcmV0IjoiYTMzZDg4ZTZhNmY0NzM4NGM3ZTE0NmJlM2JiMTIwMjE2ZGUyOTZmY2I2YTQzMjM1MTVkMGFmZTU1MjgyNzU2MCIsImV4cCI6MTc3NTkxODc3NH0.tatFh4speqaS-NzwxZW8foM0TJmVXNvkyZopI9e8rVM',
  pinataGateway: 'yellow-quickest-raccoon-303.mypinata.cloud',
})